# 网站名称
site_name: Material for MkDocs 文档
# 根url
site_url: https://github.com/Metasymbols.github.io
# 描述
site_description: null
# 作者
site_author: ruoshui
# 添加 git 存储库，导航区展示对应开源项目名称
repo_name: Metasymbols.github.io
# 添加 git 存储库，导航区展示对应开源项目地址
repo_url: https://github.com/Metasymbols/Metasymbols.github.io
# 解析为托管文档的子文件夹
edit_uri: edit/main/docs/
# 版权
copyright: Copyright &copy; 2022 - 2023 ruoshui


# 主题配置
theme:
    name: material
    custom_dir: docs/overrides
    features:
        # 代码块复制
        - content.code.copy
        # 编辑此页面按钮，未生效
        - content.action.edit
        # 查看源代码按钮，
        - content.action.view
        # # 页脚中的“上一个”和“下一个”按钮
        # - navigation.footer
    
    palette:
        # 主颜色
        primary: white
        accent: grey
    # palette:  
        # 浅色模式
        # - scheme: default
          # toggle:
            # icon: material/toggle-switch
            # name: Switch to dark mode

        # 深色模式 
        # - scheme: slate
          # toggle:
            # icon: material/toggle-switch-off-outline
            # name: Switch to light mode
        
    palette:

        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle: 
            icon: material/brightness-auto
            name: 切换跟随系统

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/theme-light-dark
            name: 切换暗模式

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/theme-light-dark
            name: 切换亮模式
    
    
    plugins:
        # 更新日期和在每个页面底部创建文档
        - git-revision-date-localized:
            enable_creation_date: true

        # 呈现所有贡献者的 GitHub 头像
        - git-committers:
            repository: squidfunk/mkdocs-material
            branch: main
        # 从 git 中提取文档的作者并将其显示在每个页面的底部。
        - git-authors
        
        # # 元文件设置
        # - meta
        # 启动内置搜索
        - search
    
    
    # 设置语言   
    extra:
        alternate:
            - name: English
              link: /en/ 
              lang: en
            - name: Chinese
              link: /zh/
              lang: zh

# 页面目录
nav:
    
    - 基础: index.md
    
    - 设置: SetUp.md
    
    